### PR TITLE
Ti SDK 7.0.0.GA Update

### PR DESCRIPTION
**Pull request by m1ga**
Ti SDK 7.0.0.GA Update 

- [x] removed playservice files
- [x] removed proguard folder
- [x] added ti.playservice module
- [x] tested with Ti SDK 7 + Ti.Maps + Ti.Goosh
- [x] send normal push to device (foreground/background)
- [x] send push to topic (foreground/background)
- [x] updated README to show subscribe to topic (+ php example)

### CODE REVIEW

**Comment by kopiro** [comment]
Hey, thank you! :)
Did you test the build?

**Comment by m1ga** [comment]
I've ended up with `[ERROR] E/ti.goosh.TiGooshModule: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference` but I thought it was just because I've added the module to an empty project and just used the democode without any GCM ID.

But it would make sense to change the whole library structure to ti.playservice because that is available with ti 7! Going to test that at the weekend and update the PR. 

**So don't merge yet!**

**Comment by m1ga** [comment]
Now everything works fine with `ti.playservices`! Updated the initial post with all the changes

**Comment by amigoni** [comment]
Awesome. Thanks so much. I am currently blocked from releasing our app due to conflicts with playservices, when do you think we'll have a this new version released?

**Comment by m1ga** [comment]
@amigoni feel free to try it out: https://github.com/m1ga/ti.goosh/blob/7aeaab951699bff0fd837ac416c9e50e416bc304/android/dist/ti.goosh-android-4.0.0.zip

**Comment by amigoni** [comment]
Awesome! Thanks so much! I really appreciate it.

**Pull request merged**
