### PR TITLE
Subscribe to topics

### PR DESCRIPTION
**Pull request by m1ga**
Adding the possibility to subscribe to topics:

**Subscribe:** 

```javascript
TiGoosh.subscribe({
	topic: "/topics/myTopic",
	success: function(e) {
		console.log("unsub done " + e);
	},
	error: function(e){
		console.error("error")
	}
})
```

**Unsubscribe:**

```javascript
TiGoosh.unsubscribe({
	topic: "/topics/myTopic",
	success: function(e) {
		console.log("unsub done " + e);
	},
	error: function(e){
		console.error("error")
	}
})
```

**PHP test:**

```php
<?php
// API access key from Google API's Console
define('API_ACCESS_KEY', '.......');
// prep the bundle
$msg = array
(
'body' => 'This is a message sent from my http server',
'title' => 'From server side',
'priority' => 'high',
'sound' => 'default',
'time_to_live' => 3600
);
$fields = array('to' => '/topics/myTopic', 'notification' => $msg);

$headers = array
(
'Authorization: key=' . API_ACCESS_KEY,
'Content-Type: application/json'
);

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'https://fcm.googleapis.com/fcm/send');
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($fields));
$result = curl_exec($ch);
curl_close($ch);
echo $result;
```

### CODE REVIEW

**Comment by m1ga** [comment]
@Jei just saw your branch so I've forked from it to create my PR

**Comment by Jei** [comment]
Thank you!
Did you try to compile the module though? I'm having problems with missing classes. I'll try again today and see if i can find the problem.

**Comment by m1ga** [comment]
With your aar files it worked without a problem. Tested it with 6.2.2.GA

**Comment by Jei** [comment]
Ok, i forgot to select the correct SDK. I used 6.2.0.GA.
I'm merging this and making a new major release, since this will not be compatible with older Titanium versions.

**Comment by m1ga** [comment]
ok, I didn't test it with an older version, but good that you found that issue 👍

**Comment by DouglasHennrich** [comment]
I have looked into `platform/res/values/version.xml` and it's using this`8487000` version of google play service?
`<integer name="google_play_services_version">8487000</integer>`

Shouldn't it be `11020000` or higher ?

**Pull request merged**
